# Generated by Django 4.2.7 on 2026-01-26 19:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address_complement",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address_number",
            field=models.CharField(blank=True, max_length=10, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address_street",
            field=models.CharField(blank=True, max_length=255, verbose_name="Rua"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="state",
            field=models.CharField(blank=True, max_length=2, verbose_name="Estado"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="zip_code",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[accounts.models.validate_brazilian_cep],
                verbose_name="CEP",
            ),
        ),
    ]
