# Generated by Django 4.2.7 on 2026-02-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "discount_percent",
                    models.IntegerField(
                        help_text="Porcentagem de desconto (0-100)",
                        verbose_name="Desconto (%)",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Válido de")),
                ("valid_to", models.DateTimeField(verbose_name="Válido até")),
                ("active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Cupom",
                "verbose_name_plural": "Cupons",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Em Processamento"),
                    ("out_for_delivery", "Em Rota de Entrega"),
                    ("completed", "Concluído"),
                    ("cancelled", "Cancelado"),
                ],
                default="processing",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("processing", "Em Processamento"),
                    ("out_for_delivery", "Em Rota de Entrega"),
                    ("completed", "Concluído"),
                    ("cancelled", "Cancelado"),
                ],
                max_length=20,
                verbose_name="Novo Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="old_status",
            field=models.CharField(
                choices=[
                    ("processing", "Em Processamento"),
                    ("out_for_delivery", "Em Rota de Entrega"),
                    ("completed", "Concluído"),
                    ("cancelled", "Cancelado"),
                ],
                max_length=20,
                verbose_name="Status Anterior",
            ),
        ),
    ]
