# Generated by Django 4.2.7 on 2026-02-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_coupon_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.coupon",
                verbose_name="Cupom de Desconto",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Desconto"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Cartão de Crédito"),
                    ("pix", "PIX"),
                    ("pay_on_delivery", "Pagamento na Entrega"),
                ],
                default="credit_card",
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
    ]
