# Generated by Django 4.2.7 on 2026-02-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_coupon_order_discount_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Em Processamento"),
                    ("out_for_delivery", "Em Rota de Entrega"),
                    ("completed", "Concluído"),
                ],
                default="processing",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("processing", "Em Processamento"),
                    ("out_for_delivery", "Em Rota de Entrega"),
                    ("completed", "Concluído"),
                ],
                max_length=20,
                verbose_name="Novo Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="old_status",
            field=models.CharField(
                choices=[
                    ("processing", "Em Processamento"),
                    ("out_for_delivery", "Em Rota de Entrega"),
                    ("completed", "Concluído"),
                ],
                max_length=20,
                verbose_name="Status Anterior",
            ),
        ),
    ]
