# Generated by Django 4.2.7 on 2026-01-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ML", "Mililitro (ml)"),
                    ("L", "Litro (L)"),
                    ("KG", "Quilograma (kg)"),
                    ("G", "Grama (g)"),
                ],
                max_length=5,
                null=True,
                verbose_name="Unidade de Medida",
            ),
        ),
    ]
